/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Namko
 */
public class Accueil_1 extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public Accueil_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneAdmin = new javax.swing.JTabbedPane();
        jPanelGeneral = new javax.swing.JPanel();
        jPanelContent = new javax.swing.JPanel();
        jLabelNom = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelMat = new javax.swing.JLabel();
        jTextFieldMat = new javax.swing.JTextField();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jPanelTitre = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        jPanelIdentite = new javax.swing.JPanel();
        jPanelTitre1 = new javax.swing.JPanel();
        jLabelTitre1 = new javax.swing.JLabel();
        jPanelContent1 = new javax.swing.JPanel();
        jLabelDateNais = new javax.swing.JLabel();
        jLabelVilleNais = new javax.swing.JLabel();
        jLabelPaysNais = new javax.swing.JLabel();
        jLabelSexe = new javax.swing.JLabel();
        jLabelDateInsc = new javax.swing.JLabel();
        jLabelEtaPre = new javax.swing.JLabel();
        jTextFieldDateNais = new javax.swing.JTextField();
        jTextFieldVilleNais = new javax.swing.JTextField();
        jTextFieldPaysNais = new javax.swing.JTextField();
        jTextFieldSexe = new javax.swing.JTextField();
        jTextFieldDateInsc = new javax.swing.JTextField();
        jTextFieldEtaPre = new javax.swing.JTextField();
        jPanelCoord = new javax.swing.JPanel();
        jPanelTitre2 = new javax.swing.JPanel();
        jLabelTitre2 = new javax.swing.JLabel();
        jPanelContent2 = new javax.swing.JPanel();
        jLabelAdr = new javax.swing.JLabel();
        jLabelCp = new javax.swing.JLabel();
        jLabelVille = new javax.swing.JLabel();
        jLabelTelDom = new javax.swing.JLabel();
        jLabelTelMob = new javax.swing.JLabel();
        jLabelMail = new javax.swing.JLabel();
        jTextFieldAdr = new javax.swing.JTextField();
        jTextFieldCp = new javax.swing.JTextField();
        jTextFieldVille = new javax.swing.JTextField();
        jTextFieldTelDom = new javax.swing.JTextField();
        jTextFieldTelMob = new javax.swing.JTextField();
        jTextFieldMail = new javax.swing.JTextField();
        jPanelPers = new javax.swing.JPanel();
        jPanelTitre3 = new javax.swing.JPanel();
        jLabelTitre3 = new javax.swing.JLabel();
        jPanelContent3 = new javax.swing.JPanel();
        jLabelContact1 = new javax.swing.JLabel();
        jLabelContact1Nom = new javax.swing.JLabel();
        jLabelContact1Prenom = new javax.swing.JLabel();
        jLabelContact1Adr = new javax.swing.JLabel();
        jLabelContact1Tel = new javax.swing.JLabel();
        jLabelContact1Mail = new javax.swing.JLabel();
        jLabelContact2 = new javax.swing.JLabel();
        jLabelContact2Nom = new javax.swing.JLabel();
        jLabelContact2Prenom = new javax.swing.JLabel();
        jLabelContact2Adr = new javax.swing.JLabel();
        jLabelContact2Tel = new javax.swing.JLabel();
        jLabelContact2Mail = new javax.swing.JLabel();
        jTextFieldContact1Nom = new javax.swing.JTextField();
        jTextFieldContact1Prenom = new javax.swing.JTextField();
        jTextFieldContact1Adr = new javax.swing.JTextField();
        jTextFieldContact1Tel = new javax.swing.JTextField();
        jTextFieldContact1Mail = new javax.swing.JTextField();
        jTextFieldContact2Nom = new javax.swing.JTextField();
        jTextFieldContact2Prenom = new javax.swing.JTextField();
        jTextFieldContact2Adr = new javax.swing.JTextField();
        jTextFieldContact2Tel = new javax.swing.JTextField();
        jTextFieldContact2Mail = new javax.swing.JTextField();
        jPanelSante = new javax.swing.JPanel();
        jPanelTitre4 = new javax.swing.JPanel();
        jLabelTitre4 = new javax.swing.JLabel();
        jPanelContent4 = new javax.swing.JPanel();
        jLabelNomMed = new javax.swing.JLabel();
        jLabelPrenomMed = new javax.swing.JLabel();
        jLabelTelMed = new javax.swing.JLabel();
        jLabelVacc = new javax.swing.JLabel();
        jLabelAll = new javax.swing.JLabel();
        jLabelRem = new javax.swing.JLabel();
        jTextFieldNomMed = new javax.swing.JTextField();
        jTextFieldPrenomMed = new javax.swing.JTextField();
        jTextFieldTelMed = new javax.swing.JTextField();
        jTextFieldVacc = new javax.swing.JTextField();
        jTextFieldAll = new javax.swing.JTextField();
        jTextFieldRem = new javax.swing.JTextField();
        jPanelDoc = new javax.swing.JPanel();
        jPanelTitre5 = new javax.swing.JPanel();
        jLabelTitre5 = new javax.swing.JLabel();
        jPanelContent5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jPanelGeneral.setBackground(new java.awt.Color(204, 204, 255));

        jPanelContent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jLabelNom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelNom.setText("Nom :");

        jLabelPrenom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPrenom.setText("Prénom :");

        jLabelMat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelMat.setText("Matricule :");

        jTextFieldMat.setText("jTextField1");

        jTextFieldNom.setText("jTextField2");

        jTextFieldPrenom.setText("jTextField3");

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMat)
                    .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrenom))
                .addGap(77, 77, 77)
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMat)
                    .addComponent(jTextFieldMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        jLabelTitre.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre.setText("GENERAL");

        javax.swing.GroupLayout jPanelTitreLayout = new javax.swing.GroupLayout(jPanelTitre);
        jPanelTitre.setLayout(jPanelTitreLayout);
        jPanelTitreLayout.setHorizontalGroup(
            jPanelTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitreLayout.setVerticalGroup(
            jPanelTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelGeneralLayout = new javax.swing.GroupLayout(jPanelGeneral);
        jPanelGeneral.setLayout(jPanelGeneralLayout);
        jPanelGeneralLayout.setHorizontalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelGeneralLayout.setVerticalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneAdmin.addTab("Général", jPanelGeneral);

        jLabelTitre1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTitre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre1.setText("IDENTITE");

        javax.swing.GroupLayout jPanelTitre1Layout = new javax.swing.GroupLayout(jPanelTitre1);
        jPanelTitre1.setLayout(jPanelTitre1Layout);
        jPanelTitre1Layout.setHorizontalGroup(
            jPanelTitre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitre1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitre1Layout.setVerticalGroup(
            jPanelTitre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitre1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelContent1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jLabelDateNais.setText("Date de naissance : ");

        jLabelVilleNais.setText("Ville de naissance :");

        jLabelPaysNais.setText("Pays de naissance :");

        jLabelSexe.setText("Sexe : ");

        jLabelDateInsc.setText("Date d'inscritption : ");

        jLabelEtaPre.setText("Etablissement précédent : ");

        jTextFieldDateNais.setText("jTextField1");

        jTextFieldVilleNais.setText("jTextField1");

        jTextFieldPaysNais.setText("jTextField1");

        jTextFieldSexe.setText("jTextField1");

        jTextFieldDateInsc.setText("jTextField1");

        jTextFieldEtaPre.setText("jTextField1");

        javax.swing.GroupLayout jPanelContent1Layout = new javax.swing.GroupLayout(jPanelContent1);
        jPanelContent1.setLayout(jPanelContent1Layout);
        jPanelContent1Layout.setHorizontalGroup(
            jPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContent1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelContent1Layout.createSequentialGroup()
                        .addComponent(jLabelEtaPre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldEtaPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContent1Layout.createSequentialGroup()
                        .addComponent(jLabelDateInsc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldDateInsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContent1Layout.createSequentialGroup()
                        .addComponent(jLabelSexe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContent1Layout.createSequentialGroup()
                        .addComponent(jLabelPaysNais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPaysNais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContent1Layout.createSequentialGroup()
                        .addComponent(jLabelVilleNais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldVilleNais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContent1Layout.createSequentialGroup()
                        .addComponent(jLabelDateNais)
                        .addGap(105, 105, 105)
                        .addComponent(jTextFieldDateNais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContent1Layout.setVerticalGroup(
            jPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContent1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateNais)
                    .addComponent(jTextFieldDateNais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVilleNais)
                    .addComponent(jTextFieldVilleNais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPaysNais)
                    .addComponent(jTextFieldPaysNais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSexe)
                    .addComponent(jTextFieldSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateInsc)
                    .addComponent(jTextFieldDateInsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEtaPre)
                    .addComponent(jTextFieldEtaPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(279, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelIdentiteLayout = new javax.swing.GroupLayout(jPanelIdentite);
        jPanelIdentite.setLayout(jPanelIdentiteLayout);
        jPanelIdentiteLayout.setHorizontalGroup(
            jPanelIdentiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdentiteLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanelTitre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(jPanelIdentiteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelIdentiteLayout.setVerticalGroup(
            jPanelIdentiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdentiteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelContent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneAdmin.addTab("Identité", jPanelIdentite);

        jPanelCoord.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitre2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTitre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre2.setText("COORDONNEES");

        javax.swing.GroupLayout jPanelTitre2Layout = new javax.swing.GroupLayout(jPanelTitre2);
        jPanelTitre2.setLayout(jPanelTitre2Layout);
        jPanelTitre2Layout.setHorizontalGroup(
            jPanelTitre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitre2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitre2Layout.setVerticalGroup(
            jPanelTitre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitre2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelContent2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jLabelAdr.setText("Adresse : ");

        jLabelCp.setText("Code postal : ");

        jLabelVille.setText("Ville : ");

        jLabelTelDom.setText("Téléphone domicile : ");

        jLabelTelMob.setText("Téléphone mobile : ");

        jLabelMail.setText("Email : ");

        jTextFieldAdr.setText("jTextField1");

        jTextFieldCp.setText("jTextField1");

        jTextFieldVille.setText("jTextField1");

        jTextFieldTelDom.setText("jTextField1");

        jTextFieldTelMob.setText("jTextField1");

        jTextFieldMail.setText("jTextField1");

        javax.swing.GroupLayout jPanelContent2Layout = new javax.swing.GroupLayout(jPanelContent2);
        jPanelContent2.setLayout(jPanelContent2Layout);
        jPanelContent2Layout.setHorizontalGroup(
            jPanelContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContent2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanelContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAdr)
                    .addComponent(jLabelCp)
                    .addComponent(jLabelVille)
                    .addComponent(jLabelTelDom)
                    .addComponent(jLabelTelMob)
                    .addComponent(jLabelMail))
                .addGap(96, 96, 96)
                .addGroup(jPanelContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTelMob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTelDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAdr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContent2Layout.setVerticalGroup(
            jPanelContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContent2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanelContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdr)
                    .addComponent(jTextFieldAdr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCp)
                    .addComponent(jTextFieldCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVille)
                    .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelDom)
                    .addComponent(jTextFieldTelDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelMob)
                    .addComponent(jTextFieldTelMob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMail)
                    .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCoordLayout = new javax.swing.GroupLayout(jPanelCoord);
        jPanelCoord.setLayout(jPanelCoordLayout);
        jPanelCoordLayout.setHorizontalGroup(
            jPanelCoordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCoordLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanelTitre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(jPanelCoordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContent2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCoordLayout.setVerticalGroup(
            jPanelCoordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCoordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelContent2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneAdmin.addTab("Coordonnées", jPanelCoord);

        jLabelTitre3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTitre3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre3.setText("PERSONNE RESPONSABLE");

        javax.swing.GroupLayout jPanelTitre3Layout = new javax.swing.GroupLayout(jPanelTitre3);
        jPanelTitre3.setLayout(jPanelTitre3Layout);
        jPanelTitre3Layout.setHorizontalGroup(
            jPanelTitre3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitre3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitre3Layout.setVerticalGroup(
            jPanelTitre3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitre3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre3, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelContent3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jLabelContact1.setText("PREMIER CONTACT");

        jLabelContact1Nom.setText("Nom : ");

        jLabelContact1Prenom.setText("Prénom : ");

        jLabelContact1Adr.setText("Adresse : ");

        jLabelContact1Tel.setText("Téléphone : ");

        jLabelContact1Mail.setText("Email : ");

        jLabelContact2.setText("SECOND CONTACT");

        jLabelContact2Nom.setText("Nom : ");

        jLabelContact2Prenom.setText("Prénom :");

        jLabelContact2Adr.setText("Adresse :");

        jLabelContact2Tel.setText("Téléphone : ");

        jLabelContact2Mail.setText("Email : ");

        jTextFieldContact1Nom.setText("jTextField1");

        jTextFieldContact1Prenom.setText("jTextField1");

        jTextFieldContact1Adr.setText("jTextField1");

        jTextFieldContact1Tel.setText("jTextField1");

        jTextFieldContact1Mail.setText("jTextField1");

        jTextFieldContact2Nom.setText("jTextField1");

        jTextFieldContact2Prenom.setText("jTextField1");

        jTextFieldContact2Adr.setText("jTextField1");

        jTextFieldContact2Tel.setText("jTextField1");

        jTextFieldContact2Mail.setText("jTextField1");

        javax.swing.GroupLayout jPanelContent3Layout = new javax.swing.GroupLayout(jPanelContent3);
        jPanelContent3.setLayout(jPanelContent3Layout);
        jPanelContent3Layout.setHorizontalGroup(
            jPanelContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContent3Layout.createSequentialGroup()
                .addGroup(jPanelContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelContent3Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabelContact1))
                    .addGroup(jPanelContent3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanelContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContent3Layout.createSequentialGroup()
                                .addComponent(jLabelContact1Prenom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldContact1Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContent3Layout.createSequentialGroup()
                                .addComponent(jLabelContact1Nom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldContact1Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContent3Layout.createSequentialGroup()
                                .addComponent(jLabelContact1Mail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldContact1Mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContent3Layout.createSequentialGroup()
                                .addComponent(jLabelContact1Adr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldContact1Adr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContent3Layout.createSequentialGroup()
                                .addComponent(jLabelContact1Tel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldContact1Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContact2)
                    .addGroup(jPanelContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelContent3Layout.createSequentialGroup()
                            .addComponent(jLabelContact2Mail)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldContact2Mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelContent3Layout.createSequentialGroup()
                            .addComponent(jLabelContact2Tel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldContact2Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelContent3Layout.createSequentialGroup()
                            .addComponent(jLabelContact2Adr)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldContact2Adr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelContent3Layout.createSequentialGroup()
                            .addComponent(jLabelContact2Prenom)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldContact2Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelContent3Layout.createSequentialGroup()
                            .addComponent(jLabelContact2Nom)
                            .addGap(74, 74, 74)
                            .addComponent(jTextFieldContact2Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(159, 159, 159))
        );
        jPanelContent3Layout.setVerticalGroup(
            jPanelContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContent3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanelContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContact1)
                    .addComponent(jLabelContact2))
                .addGap(45, 45, 45)
                .addGroup(jPanelContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContact1Nom)
                    .addComponent(jLabelContact2Nom)
                    .addComponent(jTextFieldContact1Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContact2Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContact1Prenom)
                    .addComponent(jLabelContact2Prenom)
                    .addComponent(jTextFieldContact1Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContact2Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContact1Adr)
                    .addComponent(jLabelContact2Adr)
                    .addComponent(jTextFieldContact1Adr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContact2Adr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContact1Tel)
                    .addComponent(jLabelContact2Tel)
                    .addComponent(jTextFieldContact1Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContact2Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContact1Mail)
                    .addComponent(jLabelContact2Mail)
                    .addComponent(jTextFieldContact1Mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContact2Mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(248, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPersLayout = new javax.swing.GroupLayout(jPanelPers);
        jPanelPers.setLayout(jPanelPersLayout);
        jPanelPersLayout.setHorizontalGroup(
            jPanelPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanelTitre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(jPanelPersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContent3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPersLayout.setVerticalGroup(
            jPanelPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelContent3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneAdmin.addTab("Personne responsable", jPanelPers);

        jLabelTitre4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTitre4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre4.setText("SANTE");

        javax.swing.GroupLayout jPanelTitre4Layout = new javax.swing.GroupLayout(jPanelTitre4);
        jPanelTitre4.setLayout(jPanelTitre4Layout);
        jPanelTitre4Layout.setHorizontalGroup(
            jPanelTitre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitre4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre4, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitre4Layout.setVerticalGroup(
            jPanelTitre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitre4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre4, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelContent4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jLabelNomMed.setText("Nom du médecin traitant :");

        jLabelPrenomMed.setText("Prénom du médecin traitant : ");

        jLabelTelMed.setText("Téléphone :");

        jLabelVacc.setText("Vaccination(s) :");

        jLabelAll.setText("Allergie(s) : ");

        jLabelRem.setText("Remarque(s) médicale(s) : ");

        jTextFieldNomMed.setText("jTextField1");

        jTextFieldPrenomMed.setText("jTextField1");

        jTextFieldTelMed.setText("jTextField1");

        jTextFieldVacc.setText("jTextField1");

        jTextFieldAll.setText("jTextField1");

        jTextFieldRem.setText("jTextField1");

        javax.swing.GroupLayout jPanelContent4Layout = new javax.swing.GroupLayout(jPanelContent4);
        jPanelContent4.setLayout(jPanelContent4Layout);
        jPanelContent4Layout.setHorizontalGroup(
            jPanelContent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContent4Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanelContent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelContent4Layout.createSequentialGroup()
                        .addComponent(jLabelRem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContent4Layout.createSequentialGroup()
                        .addComponent(jLabelAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContent4Layout.createSequentialGroup()
                        .addComponent(jLabelVacc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldVacc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContent4Layout.createSequentialGroup()
                        .addComponent(jLabelTelMed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldTelMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContent4Layout.createSequentialGroup()
                        .addComponent(jLabelPrenomMed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPrenomMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContent4Layout.createSequentialGroup()
                        .addComponent(jLabelNomMed)
                        .addGap(120, 120, 120)
                        .addComponent(jTextFieldNomMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContent4Layout.setVerticalGroup(
            jPanelContent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContent4Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanelContent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomMed)
                    .addComponent(jTextFieldNomMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrenomMed)
                    .addComponent(jTextFieldPrenomMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelMed)
                    .addComponent(jTextFieldTelMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVacc)
                    .addComponent(jTextFieldVacc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAll)
                    .addComponent(jTextFieldAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRem)
                    .addComponent(jTextFieldRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelSanteLayout = new javax.swing.GroupLayout(jPanelSante);
        jPanelSante.setLayout(jPanelSanteLayout);
        jPanelSanteLayout.setHorizontalGroup(
            jPanelSanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSanteLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanelTitre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(jPanelSanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContent4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSanteLayout.setVerticalGroup(
            jPanelSanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelContent4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneAdmin.addTab("Santé", jPanelSante);

        jLabelTitre5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTitre5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre5.setText("DOCUMENTS");

        javax.swing.GroupLayout jPanelTitre5Layout = new javax.swing.GroupLayout(jPanelTitre5);
        jPanelTitre5.setLayout(jPanelTitre5Layout);
        jPanelTitre5Layout.setHorizontalGroup(
            jPanelTitre5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitre5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre5, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitre5Layout.setVerticalGroup(
            jPanelTitre5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitre5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre5, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelContent5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        javax.swing.GroupLayout jPanelContent5Layout = new javax.swing.GroupLayout(jPanelContent5);
        jPanelContent5.setLayout(jPanelContent5Layout);
        jPanelContent5Layout.setHorizontalGroup(
            jPanelContent5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );
        jPanelContent5Layout.setVerticalGroup(
            jPanelContent5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelDocLayout = new javax.swing.GroupLayout(jPanelDoc);
        jPanelDoc.setLayout(jPanelDocLayout);
        jPanelDocLayout.setHorizontalGroup(
            jPanelDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanelTitre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(jPanelDocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContent5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDocLayout.setVerticalGroup(
            jPanelDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelContent5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneAdmin.addTab("Documents", jPanelDoc);

        jButton1.setText("Accueil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Partie Administrative");

        jButton3.setText("Partie Académique");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/logo-ex-7.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPaneAdmin))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Accueil_1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAdr;
    private javax.swing.JLabel jLabelAll;
    private javax.swing.JLabel jLabelContact1;
    private javax.swing.JLabel jLabelContact1Adr;
    private javax.swing.JLabel jLabelContact1Mail;
    private javax.swing.JLabel jLabelContact1Nom;
    private javax.swing.JLabel jLabelContact1Prenom;
    private javax.swing.JLabel jLabelContact1Tel;
    private javax.swing.JLabel jLabelContact2;
    private javax.swing.JLabel jLabelContact2Adr;
    private javax.swing.JLabel jLabelContact2Mail;
    private javax.swing.JLabel jLabelContact2Nom;
    private javax.swing.JLabel jLabelContact2Prenom;
    private javax.swing.JLabel jLabelContact2Tel;
    private javax.swing.JLabel jLabelCp;
    private javax.swing.JLabel jLabelDateInsc;
    private javax.swing.JLabel jLabelDateNais;
    private javax.swing.JLabel jLabelEtaPre;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelMat;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelNomMed;
    private javax.swing.JLabel jLabelPaysNais;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelPrenomMed;
    private javax.swing.JLabel jLabelRem;
    private javax.swing.JLabel jLabelSexe;
    private javax.swing.JLabel jLabelTelDom;
    private javax.swing.JLabel jLabelTelMed;
    private javax.swing.JLabel jLabelTelMob;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JLabel jLabelTitre1;
    private javax.swing.JLabel jLabelTitre2;
    private javax.swing.JLabel jLabelTitre3;
    private javax.swing.JLabel jLabelTitre4;
    private javax.swing.JLabel jLabelTitre5;
    private javax.swing.JLabel jLabelVacc;
    private javax.swing.JLabel jLabelVille;
    private javax.swing.JLabel jLabelVilleNais;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelContent1;
    private javax.swing.JPanel jPanelContent2;
    private javax.swing.JPanel jPanelContent3;
    private javax.swing.JPanel jPanelContent4;
    private javax.swing.JPanel jPanelContent5;
    private javax.swing.JPanel jPanelCoord;
    private javax.swing.JPanel jPanelDoc;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JPanel jPanelIdentite;
    private javax.swing.JPanel jPanelPers;
    private javax.swing.JPanel jPanelSante;
    private javax.swing.JPanel jPanelTitre;
    private javax.swing.JPanel jPanelTitre1;
    private javax.swing.JPanel jPanelTitre2;
    private javax.swing.JPanel jPanelTitre3;
    private javax.swing.JPanel jPanelTitre4;
    private javax.swing.JPanel jPanelTitre5;
    private javax.swing.JTabbedPane jTabbedPaneAdmin;
    private javax.swing.JTextField jTextFieldAdr;
    private javax.swing.JTextField jTextFieldAll;
    private javax.swing.JTextField jTextFieldContact1Adr;
    private javax.swing.JTextField jTextFieldContact1Mail;
    private javax.swing.JTextField jTextFieldContact1Nom;
    private javax.swing.JTextField jTextFieldContact1Prenom;
    private javax.swing.JTextField jTextFieldContact1Tel;
    private javax.swing.JTextField jTextFieldContact2Adr;
    private javax.swing.JTextField jTextFieldContact2Mail;
    private javax.swing.JTextField jTextFieldContact2Nom;
    private javax.swing.JTextField jTextFieldContact2Prenom;
    private javax.swing.JTextField jTextFieldContact2Tel;
    private javax.swing.JTextField jTextFieldCp;
    private javax.swing.JTextField jTextFieldDateInsc;
    private javax.swing.JTextField jTextFieldDateNais;
    private javax.swing.JTextField jTextFieldEtaPre;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldMat;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldNomMed;
    private javax.swing.JTextField jTextFieldPaysNais;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldPrenomMed;
    private javax.swing.JTextField jTextFieldRem;
    private javax.swing.JTextField jTextFieldSexe;
    private javax.swing.JTextField jTextFieldTelDom;
    private javax.swing.JTextField jTextFieldTelMed;
    private javax.swing.JTextField jTextFieldTelMob;
    private javax.swing.JTextField jTextFieldVacc;
    private javax.swing.JTextField jTextFieldVille;
    private javax.swing.JTextField jTextFieldVilleNais;
    // End of variables declaration//GEN-END:variables
}
