/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaprojet.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author Namko
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneAccueil = new javax.swing.JTabbedPane();
        jPanelConnexion = new javax.swing.JPanel();
        jPanelTitreConnexion = new javax.swing.JPanel();
        jLabelConnexion = new javax.swing.JLabel();
        jPanelMainContent = new javax.swing.JPanel();
        jPanelContentConnexion = new javax.swing.JPanel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelMdp = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jPasswordFieldMdp = new javax.swing.JPasswordField();
        jButtonConnect = new javax.swing.JButton();
        jPanelContentConnected = new javax.swing.JPanel();
        jLabelConnected = new javax.swing.JLabel();
        jButtonDiscon = new javax.swing.JButton();
        jButtonAccueil = new javax.swing.JButton();
        jButtonAdmin = new javax.swing.JButton();
        jButtonAca = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jPanelConnexion.setBackground(new java.awt.Color(102, 102, 102));

        jLabelConnexion.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelConnexion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConnexion.setText("Connexion");

        javax.swing.GroupLayout jPanelTitreConnexionLayout = new javax.swing.GroupLayout(jPanelTitreConnexion);
        jPanelTitreConnexion.setLayout(jPanelTitreConnexionLayout);
        jPanelTitreConnexionLayout.setHorizontalGroup(
            jPanelTitreConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreConnexionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelConnexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitreConnexionLayout.setVerticalGroup(
            jPanelTitreConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreConnexionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelConnexion, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelMainContent.setLayout(new java.awt.CardLayout());

        jPanelContentConnexion.setBackground(new java.awt.Color(204, 204, 204));
        jPanelContentConnexion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jLabelLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelLogin.setText("Login :");

        jLabelMdp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelMdp.setText("Password :");

        jButtonConnect.setText("Se connecter");

        javax.swing.GroupLayout jPanelContentConnexionLayout = new javax.swing.GroupLayout(jPanelContentConnexion);
        jPanelContentConnexion.setLayout(jPanelContentConnexionLayout);
        jPanelContentConnexionLayout.setHorizontalGroup(
            jPanelContentConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentConnexionLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanelContentConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMdp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonConnect)
                    .addGroup(jPanelContentConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldLogin)
                        .addComponent(jPasswordFieldMdp, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanelContentConnexionLayout.setVerticalGroup(
            jPanelContentConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentConnexionLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanelContentConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContentConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMdp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldMdp, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButtonConnect)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jPanelMainContent.add(jPanelContentConnexion, "cardLogin");

        jPanelContentConnected.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jLabelConnected.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelConnected.setText("Vous êtes connecté !");

        jButtonDiscon.setText("Se déconnecter");
        jButtonDiscon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContentConnectedLayout = new javax.swing.GroupLayout(jPanelContentConnected);
        jPanelContentConnected.setLayout(jPanelContentConnectedLayout);
        jPanelContentConnectedLayout.setHorizontalGroup(
            jPanelContentConnectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentConnectedLayout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addGroup(jPanelContentConnectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDiscon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelConnected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanelContentConnectedLayout.setVerticalGroup(
            jPanelContentConnectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentConnectedLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabelConnected)
                .addGap(41, 41, 41)
                .addComponent(jButtonDiscon)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jPanelMainContent.add(jPanelContentConnected, "cardConnected");

        javax.swing.GroupLayout jPanelConnexionLayout = new javax.swing.GroupLayout(jPanelConnexion);
        jPanelConnexion.setLayout(jPanelConnexionLayout);
        jPanelConnexionLayout.setHorizontalGroup(
            jPanelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConnexionLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(jPanelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTitreConnexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(107, 107, 107))
        );
        jPanelConnexionLayout.setVerticalGroup(
            jPanelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConnexionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitreConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(jPanelMainContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jTabbedPaneAccueil.addTab("Connexion", jPanelConnexion);

        jButtonAccueil.setText("Accueil");
        jButtonAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccueilActionPerformed(evt);
            }
        });

        jButtonAdmin.setText("Partie Administrative");

        jButtonAca.setText("Partie Académique");
        jButtonAca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcaActionPerformed(evt);
            }
        });

        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaprojet/view/logo-roosevelt.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAccueil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jButtonAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPaneAccueil))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccueilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAccueilActionPerformed

    private void jButtonAcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAcaActionPerformed

    private void jButtonDisconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDisconActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAca;
    private javax.swing.JButton jButtonAccueil;
    private javax.swing.JButton jButtonAdmin;
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonDiscon;
    private javax.swing.JLabel jLabelConnected;
    private javax.swing.JLabel jLabelConnexion;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMdp;
    private javax.swing.JPanel jPanelConnexion;
    private javax.swing.JPanel jPanelContentConnected;
    private javax.swing.JPanel jPanelContentConnexion;
    private javax.swing.JPanel jPanelMainContent;
    private javax.swing.JPanel jPanelTitreConnexion;
    private javax.swing.JPasswordField jPasswordFieldMdp;
    private javax.swing.JTabbedPane jTabbedPaneAccueil;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables
   //Boîte du message d'erreur
    private javax.swing.JOptionPane jop;
    
    
    //Accesseurs
    /**
     * 
     * @return jButtonAca
     */
    public JButton getjButtonAca() {
        return jButtonAca;
    }
    /**
     * 
     * @param jButtonAca 
     */
    public void setjButtonAca(JButton jButtonAca) {
        this.jButtonAca = jButtonAca;
    }
    /**
     * 
     * @return jButtonAccueil
     */
    public JButton getjButtonAccueil() {
        return jButtonAccueil;
    }
    /**
     * 
     * @param jButtonAccueil 
     */
    public void setjButtonAccueil(JButton jButtonAccueil) {
        this.jButtonAccueil = jButtonAccueil;
    }
    /**
     * 
     * @return jButtonAdmin
     */
    public JButton getjButtonAdmin() {
        return jButtonAdmin;
    }
    /**
     * 
     * @param jButtonAdmin 
     */
    public void setjButtonAdmin(JButton jButtonAdmin) {
        this.jButtonAdmin = jButtonAdmin;
    }
    /**
     * 
     * @return jButtonConnect
     */
    public JButton getjButtonConnect() {
        return jButtonConnect;
    }
    /**
     * 
     * @param jButtonConnect 
     */
    public void setjButtonConnect(JButton jButtonConnect) {
        this.jButtonConnect = jButtonConnect;
    }
    /**
     * 
     * @return jLabelConnexion
     */
    public JLabel getjLabelConnexion() {
        return jLabelConnexion;
    }
    /**
     * 
     * @param jLabelConnexion 
     */
    public void setjLabelConnexion(JLabel jLabelConnexion) {
        this.jLabelConnexion = jLabelConnexion;
    }
    /**
     * 
     * @return jLabelLogin
     */
    public JLabel getjLabelLogin() {
        return jLabelLogin;
    }
    /**
     * 
     * @param jLabelLogin 
     */
    public void setjLabelLogin(JLabel jLabelLogin) {
        this.jLabelLogin = jLabelLogin;
    }
    /**
     * 
     * @return jLabelLogo
     */
    public JLabel getjLabelLogo() {
        return jLabelLogo;
    }
    /**
     * 
     * @param jLabelLogo 
     */
    public void setjLabelLogo(JLabel jLabelLogo) {
        this.jLabelLogo = jLabelLogo;
    }
    /**
     * 
     * @return jLabelMdp
     */
    public JLabel getjLabelMdp() {
        return jLabelMdp;
    }
    /**
     * 
     * @param jLabelMdp 
     */
    public void setjLabelMdp(JLabel jLabelMdp) {
        this.jLabelMdp = jLabelMdp;
    }
    /**
     * 
     * @return jPanelConnexion
     */
    public JPanel getjPanelConnexion() {
        return jPanelConnexion;
    }
    /**
     * 
     * @param jPanelConnexion 
     */
    public void setjPanelConnexion(JPanel jPanelConnexion) {
        this.jPanelConnexion = jPanelConnexion;
    }
    /**
     * 
     * @return jPanelContentConnexion
     */
    public JPanel getjPanelContentConnexion() {
        return jPanelContentConnexion;
    }
    /**
     * 
     * @param jPanelContentConnexion 
     */
    public void setjPanelContentConnexion(JPanel jPanelContentConnexion) {
        this.jPanelContentConnexion = jPanelContentConnexion;
    }
    /**
     * 
     * @return jPanelTitreConnexion
     */
    public JPanel getjPanelTitreConnexion() {
        return jPanelTitreConnexion;
    }
    /**
     * 
     * @param jPanelTitreConnexion 
     */
    public void setjPanelTitreConnexion(JPanel jPanelTitreConnexion) {
        this.jPanelTitreConnexion = jPanelTitreConnexion;
    }
    /**
     * 
     * @return jPasswordFieldMdp
     */
    public JPasswordField getjPasswordFieldMdp() {
        return jPasswordFieldMdp;
    }
    /**
     * 
     * @param jPasswordFieldMdp 
     */
    public void setjPasswordFieldMdp(JPasswordField jPasswordFieldMdp) {
        this.jPasswordFieldMdp = jPasswordFieldMdp;
    }
    /**
     * 
     * @return jTabbedPaneAccueil
     */
    public JTabbedPane getjTabbedPaneAccueil() {
        return jTabbedPaneAccueil;
    }
    /**
     * 
     * @param jTabbedPaneAccueil 
     */
    public void setjTabbedPaneAccueil(JTabbedPane jTabbedPaneAccueil) {
        this.jTabbedPaneAccueil = jTabbedPaneAccueil;
    }
    /**
     * 
     * @return jTextFieldLogin
     */
    public JTextField getjTextFieldLogin() {
        return jTextFieldLogin;
    }
    /**
     * 
     * @param jTextFieldLogin 
     */
    public void setjTextFieldLogin(JTextField jTextFieldLogin) {
        this.jTextFieldLogin = jTextFieldLogin;
    }
    /**
     * 
     * @return jButtonDiscon
     */
    public JButton getjButtonDiscon() {
        return jButtonDiscon;
    }
    /**
     * 
     * @param jButtonDiscon 
     */
    public void setjButtonDiscon(JButton jButtonDiscon) {
        this.jButtonDiscon = jButtonDiscon;
    }
    /**
     * 
     * @return jLabelConnected
     */
    public JLabel getjLabelConnected() {
        return jLabelConnected;
    }
    /**
     * 
     * @param jLabelConnected 
     */
    public void setjLabelConnected(JLabel jLabelConnected) {
        this.jLabelConnected = jLabelConnected;
    }
    /**
     * 
     * @return jPanelContentConnected
     */
    public JPanel getjPanelContentConnected() {
        return jPanelContentConnected;
    }
    /**
     * 
     * @param jPanelContentConnected 
     */
    public void setjPanelContentConnected(JPanel jPanelContentConnected) {
        this.jPanelContentConnected = jPanelContentConnected;
    }
    /**
     * 
     * @return jPanelMainContent
     */
    public JPanel getjPanelMainContent() {
        return jPanelMainContent;
    }
    /**
     * 
     * @param jPanelMainContent 
     */
    public void setjPanelMainContent(JPanel jPanelMainContent) {
        this.jPanelMainContent = jPanelMainContent;
    }
    /**
     * 
     * @return jop
     */
    public JOptionPane getJop() {
        return jop;
    }
    /**
     * 
     * @param jop 
     */
    public void setJop(JOptionPane jop) {
        this.jop = jop;
    }


}





