/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaprojet.view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javaprojet.model.bdd.DBconnexion;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Namko
 */
public class Accueil_2 extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public Accueil_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneAdmin = new javax.swing.JTabbedPane();
        jPanelRech = new javax.swing.JPanel();
        jComboBoxReClasse = new javax.swing.JComboBox<>();
        jButtonReChoixClasse = new javax.swing.JButton();
        jButtonReChoixEtu = new javax.swing.JButton();
        jComboBoxReEtu = new javax.swing.JComboBox<>();
        jPanelGest = new javax.swing.JPanel();
        jComboBoxMatiere = new javax.swing.JComboBox<>();
        jComboBoxEtudiantMat = new javax.swing.JComboBox<>();
        jButtonOkMatiere = new javax.swing.JButton();
        jButtonChoixMatiere = new javax.swing.JButton();
        jPanelNotes = new javax.swing.JPanel();
        jPanelContentNotes = new javax.swing.JPanel();
        jScrollPaneTable = new javax.swing.JScrollPane();
        jTableNotes = new javax.swing.JTable();
        jButtonChoixLigne = new javax.swing.JButton();
        jLabelModifyNom = new javax.swing.JLabel();
        jTextFieldModifyNom = new javax.swing.JTextField();
        jLabelModifyMat = new javax.swing.JLabel();
        jTextFieldModifyMat = new javax.swing.JTextField();
        jLabelNoteMoyenne = new javax.swing.JLabel();
        jTextFieldModifyNote = new javax.swing.JTextField();
        jButtonNotesModifier = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jPanelTitreNotes = new javax.swing.JPanel();
        jLabelTitreNotes = new javax.swing.JLabel();
        jButtonAccueil = new javax.swing.JButton();
        jButtonAdmin = new javax.swing.JButton();
        jButtonAca = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jPanelRech.setBackground(new java.awt.Color(102, 102, 102));

        jComboBoxReClasse.setModel(new javax.swing.DefaultComboBoxModel<>());
        ResultSet resClasse=null;
        Statement stmt2=null;

        try{
            javaprojet.model.bdd.DBconnexion.connexionDB();
            stmt2= DBconnexion.getConn().createStatement();
            String ClassSelect="SELECT * FROM `classe`";
            System.out.println("DEBUG / USERLOGIN REQUEST"+ClassSelect);
            resClasse=stmt2.executeQuery(ClassSelect);
            while(resClasse.next()){
                jComboBoxReClasse.addItem(resClasse.getString("NomClasse"));
            }
        }
        catch (SQLException SQLe) {
            System.out.println("Probleme lors de la recherche dans la BDD "+SQLe.getMessage());

        }

        jButtonReChoixClasse.setText("Ok");

        jButtonReChoixEtu.setText("Choix");
        jButtonReChoixEtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReChoixEtuActionPerformed(evt);
            }
        });

        jComboBoxReEtu.setModel(new javax.swing.DefaultComboBoxModel<>());

        javax.swing.GroupLayout jPanelRechLayout = new javax.swing.GroupLayout(jPanelRech);
        jPanelRech.setLayout(jPanelRechLayout);
        jPanelRechLayout.setHorizontalGroup(
            jPanelRechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRechLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addGroup(jPanelRechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRechLayout.createSequentialGroup()
                        .addComponent(jComboBoxReClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jPanelRechLayout.createSequentialGroup()
                        .addComponent(jComboBoxReEtu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22)))
                .addGroup(jPanelRechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonReChoixClasse)
                    .addComponent(jButtonReChoixEtu))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        jPanelRechLayout.setVerticalGroup(
            jPanelRechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRechLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanelRechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxReClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReChoixClasse))
                .addGap(18, 18, 18)
                .addGroup(jPanelRechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReChoixEtu)
                    .addComponent(jComboBoxReEtu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(537, Short.MAX_VALUE))
        );

        jTabbedPaneAdmin.addTab("Recherche par classe", jPanelRech);

        jPanelGest.setBackground(new java.awt.Color(102, 102, 102));

        jComboBoxMatiere.setModel(new javax.swing.DefaultComboBoxModel<>());
        ResultSet res=null;
        Statement stmt=null;
        int nbp = 0;
        try{
            javaprojet.model.bdd.DBconnexion.connexionDB();
            stmt= DBconnexion.getConn().createStatement();
            String ClassSelect="SELECT * FROM `matiere`";
            System.out.println("DEBUG / USERLOGIN REQUEST"+ClassSelect);
            res=stmt.executeQuery(ClassSelect);
            while(res.next()){
                jComboBoxMatiere.addItem(res.getString("nomMat"));
            }
            stmt.close();
        }
        catch (SQLException SQLe) {
            System.out.println("Probleme lors de la recherche dans la BDD "+SQLe.getMessage());

        }

        jComboBoxEtudiantMat.setModel(new javax.swing.DefaultComboBoxModel<>());

        jButtonOkMatiere.setText("OK");

        jButtonChoixMatiere.setText("Choix");

        javax.swing.GroupLayout jPanelGestLayout = new javax.swing.GroupLayout(jPanelGest);
        jPanelGest.setLayout(jPanelGestLayout);
        jPanelGestLayout.setHorizontalGroup(
            jPanelGestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGestLayout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addGroup(jPanelGestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBoxEtudiantMat, 0, 150, Short.MAX_VALUE)
                    .addComponent(jComboBoxMatiere, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jPanelGestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOkMatiere)
                    .addComponent(jButtonChoixMatiere))
                .addGap(246, 246, 246))
        );
        jPanelGestLayout.setVerticalGroup(
            jPanelGestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(jPanelGestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOkMatiere)
                    .addComponent(jComboBoxMatiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEtudiantMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChoixMatiere))
                .addContainerGap(483, Short.MAX_VALUE))
        );

        jTabbedPaneAdmin.addTab("Gestion par matière", jPanelGest);

        jPanelNotes.setBackground(new java.awt.Color(102, 102, 102));

        jPanelContentNotes.setBackground(new java.awt.Color(102, 102, 102));
        jPanelContentNotes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jTableNotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneTable.setViewportView(jTableNotes);
        jTableNotes.setAutoCreateRowSorter(true);

        jButtonChoixLigne.setText("Valider Choix Ligne");

        jLabelModifyNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelModifyNom.setText("Nom : ");

        jLabelModifyMat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelModifyMat.setText("Matière : ");

        jTextFieldModifyMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModifyMatActionPerformed(evt);
            }
        });

        jLabelNoteMoyenne.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNoteMoyenne.setText("Moyenne : ");

        jButtonNotesModifier.setText("Modifier");

        jButtonRefresh.setText("Rafraichir le tableau");

        javax.swing.GroupLayout jPanelContentNotesLayout = new javax.swing.GroupLayout(jPanelContentNotes);
        jPanelContentNotes.setLayout(jPanelContentNotesLayout);
        jPanelContentNotesLayout.setHorizontalGroup(
            jPanelContentNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentNotesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelModifyNom, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldModifyNom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanelContentNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContentNotesLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButtonNotesModifier)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRefresh))
                    .addGroup(jPanelContentNotesLayout.createSequentialGroup()
                        .addGroup(jPanelContentNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonChoixLigne)
                            .addGroup(jPanelContentNotesLayout.createSequentialGroup()
                                .addComponent(jLabelModifyMat)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldModifyMat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(101, 101, 101)
                        .addComponent(jLabelNoteMoyenne)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldModifyNote, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelContentNotesLayout.createSequentialGroup()
                .addComponent(jScrollPaneTable)
                .addContainerGap())
        );
        jPanelContentNotesLayout.setVerticalGroup(
            jPanelContentNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentNotesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonChoixLigne)
                .addGap(18, 18, 18)
                .addGroup(jPanelContentNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModifyNom)
                    .addComponent(jTextFieldModifyNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelModifyMat)
                    .addComponent(jTextFieldModifyMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNoteMoyenne)
                    .addComponent(jTextFieldModifyNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanelContentNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNotesModifier)
                    .addComponent(jButtonRefresh))
                .addGap(32, 32, 32))
        );

        jLabelTitreNotes.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTitreNotes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitreNotes.setText("NOTES");

        javax.swing.GroupLayout jPanelTitreNotesLayout = new javax.swing.GroupLayout(jPanelTitreNotes);
        jPanelTitreNotes.setLayout(jPanelTitreNotesLayout);
        jPanelTitreNotesLayout.setHorizontalGroup(
            jPanelTitreNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreNotesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreNotes, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitreNotesLayout.setVerticalGroup(
            jPanelTitreNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreNotesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreNotes, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelNotesLayout = new javax.swing.GroupLayout(jPanelNotes);
        jPanelNotes.setLayout(jPanelNotesLayout);
        jPanelNotesLayout.setHorizontalGroup(
            jPanelNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotesLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanelTitreNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelNotesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContentNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelNotesLayout.setVerticalGroup(
            jPanelNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitreNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelContentNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneAdmin.addTab("Modification notes", jPanelNotes);

        jButtonAccueil.setText("Accueil");
        jButtonAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccueilActionPerformed(evt);
            }
        });

        jButtonAdmin.setText("Partie Administrative");

        jButtonAca.setText("Partie Académique");
        jButtonAca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcaActionPerformed(evt);
            }
        });

        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaprojet/view/logo-roosevelt.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAccueil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jButtonAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPaneAdmin))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccueilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAccueilActionPerformed

    private void jButtonAcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAcaActionPerformed

    private void jButtonReChoixEtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReChoixEtuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReChoixEtuActionPerformed

    private void jTextFieldModifyMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModifyMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModifyMatActionPerformed

//Accesseurs
    /**
     * 
     * @return jButtonAca
     */
    public JButton getjButtonAca() {
        return jButtonAca;
    }
    /**
     * 
     * @param jButtonAca 
     */
    public void setjButtonAca(JButton jButtonAca) {
        this.jButtonAca = jButtonAca;
    }
    /**
     * 
     * @return jButtonAccueil
     */
    public JButton getjButtonAccueil() {
        return jButtonAccueil;
    }
    /**
     * 
     * @param jButtonAccueil 
     */
    public void setjButtonAccueil(JButton jButtonAccueil) {
        this.jButtonAccueil = jButtonAccueil;
    }
    /**
     * 
     * @return jButtonAdmin
     */
    public JButton getjButtonAdmin() {
        return jButtonAdmin;
    }
    /**
     * 
     * @param jButtonAdmin 
     */
    public void setjButtonAdmin(JButton jButtonAdmin) {
        this.jButtonAdmin = jButtonAdmin;
    }
    /**
     * 
     * @return jLabelLogo
     */
    public JLabel getjLabelLogo() {
        return jLabelLogo;
    }
    /**
     * 
     * @param jLabelLogo 
     */
    public void setjLabelLogo(JLabel jLabelLogo) {
        this.jLabelLogo = jLabelLogo;
    }
    /**
     * 
     * @return jLabelTitreNotes
     */
    public JLabel getjLabelTitreNotes() {
        return jLabelTitreNotes;
    }
    /**
     * 
     * @param jLabelTitreNotes 
     */
    public void setjLabelTitreNotes(JLabel jLabelTitreNotes) {
        this.jLabelTitreNotes = jLabelTitreNotes;
    }
    /**
     * 
     * @return jPanelContentNotes
     */
    public JPanel getjPanelContentNotes() {
        return jPanelContentNotes;
    }
    /**
     * 
     * @param jPanelContentNotes 
     */
    public void setjPanelContentNotes(JPanel jPanelContentNotes) {
        this.jPanelContentNotes = jPanelContentNotes;
    }
    /**
     * 
     * @return jPanelGest
     */
    public JPanel getjPanelGest() {
        return jPanelGest;
    }
    /**
     * 
     * @param jPanelGest 
     */
    public void setjPanelGest(JPanel jPanelGest) {
        this.jPanelGest = jPanelGest;
    }
    /**
     * 
     * @return jPanelNotes
     */
    public JPanel getjPanelNotes() {
        return jPanelNotes;
    }
    /**
     * 
     * @param jPanelNotes 
     */
    public void setjPanelNotes(JPanel jPanelNotes) {
        this.jPanelNotes = jPanelNotes;
    }
    /**
     * 
     * @return jPanelRech
     */
    public JPanel getjPanelRech() {
        return jPanelRech;
    }
    /**
     * 
     * @param jPanelRech 
     */
    public void setjPanelRech(JPanel jPanelRech) {
        this.jPanelRech = jPanelRech;
    }
    /**
     * 
     * @return jPanelTitreNotes
     */
    public JPanel getjPanelTitreNotes() {
        return jPanelTitreNotes;
    }
    /**
     * 
     * @param jPanelTitreNotes 
     */
    public void setjPanelTitreNotes(JPanel jPanelTitreNotes) {
        this.jPanelTitreNotes = jPanelTitreNotes;
    }
    /**
     * 
     * @return jTabbedPaneAdmin
     */
    public JTabbedPane getjTabbedPaneAdmin() {
        return jTabbedPaneAdmin;
    }
    /**
     * 
     * @param jTabbedPaneAdmin 
     */
    public void setjTabbedPaneAdmin(JTabbedPane jTabbedPaneAdmin) {
        this.jTabbedPaneAdmin = jTabbedPaneAdmin;
    }
    /**
     * 
     * @return jButtonChoixMatiere
     */
    public JButton getjButtonChoixMatiere() {
        return jButtonChoixMatiere;
    }
    /**
     * 
     * @param jButtonChoixMatiere 
     */
    public void setjButtonChoixMatiere(JButton jButtonChoixMatiere) {
        this.jButtonChoixMatiere = jButtonChoixMatiere;
    }
    /**
     * 
     * @return jButtonOkMatiere
     */
    public JButton getjButtonOkMatiere() {
        return jButtonOkMatiere;
    }
    /**
     * 
     * @param jButtonOkMatiere 
     */
    public void setjButtonOkMatiere(JButton jButtonOkMatiere) {
        this.jButtonOkMatiere = jButtonOkMatiere;
    }
    /**
     * 
     * @return jComboBoxEtudiantMat
     */
    public JComboBox<String> getjComboBoxEtudiantMat() {
        return jComboBoxEtudiantMat;
    }
    /**
     * 
     * @param jComboBoxEtudiantMat 
     */
    public void setjComboBoxEtudiantMat(JComboBox<String> jComboBoxEtudiantMat) {
        this.jComboBoxEtudiantMat = jComboBoxEtudiantMat;
    }
    /**
     * 
     * @return jComboBoxMatiere
     */
    public JComboBox<String> getjComboBoxMatiere() {
        return jComboBoxMatiere;
    }
    /**
     * 
     * @param jComboBoxMatiere 
     */
    public void setjComboBoxMatiere(JComboBox<String> jComboBoxMatiere) {
        this.jComboBoxMatiere = jComboBoxMatiere;
    }
    /**
     * 
     * @return jScrollPaneTable
     */
    public JScrollPane getjScrollPaneTable() {
        return jScrollPaneTable;
    }
    /**
     * 
     * @param jScrollPaneTable 
     */
    public void setjScrollPaneTable(JScrollPane jScrollPaneTable) {
        this.jScrollPaneTable = jScrollPaneTable;
    }
    /**
     * 
     * @return jTableNotes
     */
    public JTable getjTableNotes() {
        return jTableNotes;
    }
    /**
     * 
     * @param jTableNotes 
     */
    public void setjTableNotes(JTable jTableNotes) {
        this.jTableNotes = jTableNotes;
    }
    /**
     * 
     * @return jComboBoxReClasse
     */
    public JComboBox<String> getjComboBoxReClasse() {
        return jComboBoxReClasse;
    }
    /**
     * 
     * @param jComboBoxReClasse 
     */
    public void setjComboBoxReClasse(JComboBox<String> jComboBoxReClasse) {
        this.jComboBoxReClasse = jComboBoxReClasse;
    }
    /**
     * 
     * @return jComboBoxReEtu
     */
    public JComboBox<String> getjComboBoxReEtu() {
        return jComboBoxReEtu;
    }
    /**
     * 
     * @param jComboBoxReEtu 
     */
    public void setjComboBoxReEtu(JComboBox<String> jComboBoxReEtu) {
        this.jComboBoxReEtu = jComboBoxReEtu;
    }
    /**
     * 
     * @return jButtonReChoixClasse
     */
    public JButton getjButtonReChoixClasse() {
        return jButtonReChoixClasse;
    }
    /**
     * 
     * @param jButtonReChoixClasse 
     */
    public void setjButtonReChoixClasse(JButton jButtonReChoixClasse) {
        this.jButtonReChoixClasse = jButtonReChoixClasse;
    }
    /**
     * 
     * @return jButtonReChoixEtu
     */
    public JButton getjButtonReChoixEtu() {
        return jButtonReChoixEtu;
    }
    /**
     * 
     * @param jButtonReChoixEtu 
     */
    public void setjButtonReChoixEtu(JButton jButtonReChoixEtu) {
        this.jButtonReChoixEtu = jButtonReChoixEtu;
    }
    /**
     * 
     * @return jButtonChoixLigne
     */
    public JButton getjButtonChoixLigne() {
        return jButtonChoixLigne;
    }
    /**
     * 
     * @param jButtonChoixLigne 
     */
    public void setjButtonChoixLigne(JButton jButtonChoixLigne) {
        this.jButtonChoixLigne = jButtonChoixLigne;
    }
    /**
     * 
     * @return jButtonNotesModifier
     */
    public JButton getjButtonNotesModifier() {
        return jButtonNotesModifier;
    }
    /**
     * 
     * @param jButtonNotesModifier 
     */
    public void setjButtonNotesModifier(JButton jButtonNotesModifier) {
        this.jButtonNotesModifier = jButtonNotesModifier;
    }
    /**
     * 
     * @return jLabelModifyMat
     */
    public JLabel getjLabelModifyMat() {
        return jLabelModifyMat;
    }
    /**
     * 
     * @param jLabelModifyMat 
     */
    public void setjLabelModifyMat(JLabel jLabelModifyMat) {
        this.jLabelModifyMat = jLabelModifyMat;
    }
    /**
     * 
     * @return jLabelModifyNom
     */
    public JLabel getjLabelModifyNom() {
        return jLabelModifyNom;
    }
    /**
     * 
     * @param jLabelModifyNom 
     */
    public void setjLabelModifyNom(JLabel jLabelModifyNom) {
        this.jLabelModifyNom = jLabelModifyNom;
    }
    /**
     * 
     * @return jLabelNoteMoyenne
     */
    public JLabel getjLabelNoteMoyenne() {
        return jLabelNoteMoyenne;
    }
    /**
     * 
     * @param jLabelNoteMoyenne 
     */
    public void setjLabelNoteMoyenne(JLabel jLabelNoteMoyenne) {
        this.jLabelNoteMoyenne = jLabelNoteMoyenne;
    }
    /**
     * 
     * @return jTextFieldModifyMat
     */
    public JTextField getjTextFieldModifyMat() {
        return jTextFieldModifyMat;
    }
    /**
     * 
     * @param jTextFieldModifyMat 
     */
    public void setjTextFieldModifyMat(JTextField jTextFieldModifyMat) {
        this.jTextFieldModifyMat = jTextFieldModifyMat;
    }
    /**
     * 
     * @return jTextFieldModifyNom
     */
    public JTextField getjTextFieldModifyNom() {
        return jTextFieldModifyNom;
    }
    /**
     * 
     * @param jTextFieldModifyNom 
     */
    public void setjTextFieldModifyNom(JTextField jTextFieldModifyNom) {
        this.jTextFieldModifyNom = jTextFieldModifyNom;
    }
    /**
     * 
     * @return jTextFieldModifyNote
     */
    public JTextField getjTextFieldModifyNote() {
        return jTextFieldModifyNote;
    }
    /**
     * 
     * @param jTextFieldModifyNote 
     */
    public void setjTextFieldModifyNote(JTextField jTextFieldModifyNote) {
        this.jTextFieldModifyNote = jTextFieldModifyNote;
    }
    /**
     * 
     * @return jButtonRefresh
     */
    public JButton getjButtonRefresh() {
        return jButtonRefresh;
    }
    /**
     * 
     * @param jButtonRefresh 
     */
    public void setjButtonRefresh(JButton jButtonRefresh) {
        this.jButtonRefresh = jButtonRefresh;
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAca;
    private javax.swing.JButton jButtonAccueil;
    private javax.swing.JButton jButtonAdmin;
    private javax.swing.JButton jButtonChoixLigne;
    private javax.swing.JButton jButtonChoixMatiere;
    private javax.swing.JButton jButtonNotesModifier;
    private javax.swing.JButton jButtonOkMatiere;
    private javax.swing.JButton jButtonReChoixClasse;
    private javax.swing.JButton jButtonReChoixEtu;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JComboBox<String> jComboBoxEtudiantMat;
    private javax.swing.JComboBox<String> jComboBoxMatiere;
    private javax.swing.JComboBox<String> jComboBoxReClasse;
    private javax.swing.JComboBox<String> jComboBoxReEtu;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelModifyMat;
    private javax.swing.JLabel jLabelModifyNom;
    private javax.swing.JLabel jLabelNoteMoyenne;
    private javax.swing.JLabel jLabelTitreNotes;
    private javax.swing.JPanel jPanelContentNotes;
    private javax.swing.JPanel jPanelGest;
    private javax.swing.JPanel jPanelNotes;
    private javax.swing.JPanel jPanelRech;
    private javax.swing.JPanel jPanelTitreNotes;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JTabbedPane jTabbedPaneAdmin;
    private javax.swing.JTable jTableNotes;
    private javax.swing.JTextField jTextFieldModifyMat;
    private javax.swing.JTextField jTextFieldModifyNom;
    private javax.swing.JTextField jTextFieldModifyNote;
    // End of variables declaration//GEN-END:variables
}
