/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaprojet.view;

/**
 *
 * @author Namko
 */
public class Accueil_1 extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public Accueil_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneAdmin = new javax.swing.JTabbedPane();
        jPanelGeneral = new javax.swing.JPanel();
        jPanelContentGen = new javax.swing.JPanel();
        jLabelNom = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelMat = new javax.swing.JLabel();
        jTextFieldMat = new javax.swing.JTextField();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jPanelTitreGen = new javax.swing.JPanel();
        jLabelTitreGen = new javax.swing.JLabel();
        jPanelIdentite = new javax.swing.JPanel();
        jPanelTitreIdentite = new javax.swing.JPanel();
        jLabelTitreIdentite = new javax.swing.JLabel();
        jPanelContentIdentite = new javax.swing.JPanel();
        jLabelDateNais = new javax.swing.JLabel();
        jLabelVilleNais = new javax.swing.JLabel();
        jLabelPaysNais = new javax.swing.JLabel();
        jLabelSexe = new javax.swing.JLabel();
        jLabelDateInsc = new javax.swing.JLabel();
        jLabelEtaPre = new javax.swing.JLabel();
        jTextFieldDateNais = new javax.swing.JTextField();
        jTextFieldVilleNais = new javax.swing.JTextField();
        jTextFieldPaysNais = new javax.swing.JTextField();
        jTextFieldSexe = new javax.swing.JTextField();
        jTextFieldDateInsc = new javax.swing.JTextField();
        jTextFieldEtaPre = new javax.swing.JTextField();
        jPanelCoord = new javax.swing.JPanel();
        jPanelTitreCoord = new javax.swing.JPanel();
        jLabelTitreCoord = new javax.swing.JLabel();
        jPanelContentCoord = new javax.swing.JPanel();
        jLabelAdr = new javax.swing.JLabel();
        jLabelCp = new javax.swing.JLabel();
        jLabelVille = new javax.swing.JLabel();
        jLabelTelDom = new javax.swing.JLabel();
        jLabelTelMob = new javax.swing.JLabel();
        jLabelMail = new javax.swing.JLabel();
        jTextFieldAdr = new javax.swing.JTextField();
        jTextFieldCp = new javax.swing.JTextField();
        jTextFieldVille = new javax.swing.JTextField();
        jTextFieldTelDom = new javax.swing.JTextField();
        jTextFieldTelMob = new javax.swing.JTextField();
        jTextFieldMail = new javax.swing.JTextField();
        jPanelPers = new javax.swing.JPanel();
        jPanelTitrePers = new javax.swing.JPanel();
        jLabelTitrePers = new javax.swing.JLabel();
        jPanelContentPers = new javax.swing.JPanel();
        jLabelContact1 = new javax.swing.JLabel();
        jLabelContact1Nom = new javax.swing.JLabel();
        jLabelContact1Prenom = new javax.swing.JLabel();
        jLabelContact1Adr = new javax.swing.JLabel();
        jLabelContact1Tel = new javax.swing.JLabel();
        jLabelContact1Mail = new javax.swing.JLabel();
        jLabelContact2 = new javax.swing.JLabel();
        jLabelContact2Nom = new javax.swing.JLabel();
        jLabelContact2Prenom = new javax.swing.JLabel();
        jLabelContact2Adr = new javax.swing.JLabel();
        jLabelContact2Tel = new javax.swing.JLabel();
        jLabelContact2Mail = new javax.swing.JLabel();
        jTextFieldContact1Nom = new javax.swing.JTextField();
        jTextFieldContact1Prenom = new javax.swing.JTextField();
        jTextFieldContact1Adr = new javax.swing.JTextField();
        jTextFieldContact1Tel = new javax.swing.JTextField();
        jTextFieldContact1Mail = new javax.swing.JTextField();
        jTextFieldContact2Nom = new javax.swing.JTextField();
        jTextFieldContact2Prenom = new javax.swing.JTextField();
        jTextFieldContact2Adr = new javax.swing.JTextField();
        jTextFieldContact2Tel = new javax.swing.JTextField();
        jTextFieldContact2Mail = new javax.swing.JTextField();
        jPanelSante = new javax.swing.JPanel();
        jPanelTitreSante = new javax.swing.JPanel();
        jLabelTitreSante = new javax.swing.JLabel();
        jPanelContentSante = new javax.swing.JPanel();
        jLabelNomMed = new javax.swing.JLabel();
        jLabelPrenomMed = new javax.swing.JLabel();
        jLabelTelMed = new javax.swing.JLabel();
        jLabelVacc = new javax.swing.JLabel();
        jLabelAll = new javax.swing.JLabel();
        jLabelRem = new javax.swing.JLabel();
        jTextFieldNomMed = new javax.swing.JTextField();
        jTextFieldPrenomMed = new javax.swing.JTextField();
        jTextFieldTelMed = new javax.swing.JTextField();
        jTextFieldVacc = new javax.swing.JTextField();
        jTextFieldAll = new javax.swing.JTextField();
        jTextFieldRem = new javax.swing.JTextField();
        jPanelDoc = new javax.swing.JPanel();
        jPanelTitreDoc = new javax.swing.JPanel();
        jLabelTitreDoc = new javax.swing.JLabel();
        jPanelContentDoc = new javax.swing.JPanel();
        jButtonAccueil = new javax.swing.JButton();
        jButtonAdmin = new javax.swing.JButton();
        jButtonAca = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jPanelGeneral.setBackground(new java.awt.Color(204, 204, 255));

        jPanelContentGen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jLabelNom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelNom.setText("Nom :");

        jLabelPrenom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPrenom.setText("Prénom :");

        jLabelMat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelMat.setText("Matricule :");

        jTextFieldMat.setText("jTextField1");

        jTextFieldNom.setText("jTextField2");

        jTextFieldPrenom.setText("jTextField3");

        javax.swing.GroupLayout jPanelContentGenLayout = new javax.swing.GroupLayout(jPanelContentGen);
        jPanelContentGen.setLayout(jPanelContentGenLayout);
        jPanelContentGenLayout.setHorizontalGroup(
            jPanelContentGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentGenLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanelContentGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMat)
                    .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrenom))
                .addGap(77, 77, 77)
                .addGroup(jPanelContentGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContentGenLayout.setVerticalGroup(
            jPanelContentGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentGenLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanelContentGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMat)
                    .addComponent(jTextFieldMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanelContentGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanelContentGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        jLabelTitreGen.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTitreGen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitreGen.setText("GENERAL");

        javax.swing.GroupLayout jPanelTitreGenLayout = new javax.swing.GroupLayout(jPanelTitreGen);
        jPanelTitreGen.setLayout(jPanelTitreGenLayout);
        jPanelTitreGenLayout.setHorizontalGroup(
            jPanelTitreGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreGenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreGen, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitreGenLayout.setVerticalGroup(
            jPanelTitreGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreGenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreGen, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelGeneralLayout = new javax.swing.GroupLayout(jPanelGeneral);
        jPanelGeneral.setLayout(jPanelGeneralLayout);
        jPanelGeneralLayout.setHorizontalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanelTitreGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContentGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelGeneralLayout.setVerticalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitreGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelContentGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneAdmin.addTab("Général", jPanelGeneral);

        jLabelTitreIdentite.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTitreIdentite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitreIdentite.setText("IDENTITE");

        javax.swing.GroupLayout jPanelTitreIdentiteLayout = new javax.swing.GroupLayout(jPanelTitreIdentite);
        jPanelTitreIdentite.setLayout(jPanelTitreIdentiteLayout);
        jPanelTitreIdentiteLayout.setHorizontalGroup(
            jPanelTitreIdentiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreIdentiteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreIdentite, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitreIdentiteLayout.setVerticalGroup(
            jPanelTitreIdentiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreIdentiteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreIdentite, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelContentIdentite.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jLabelDateNais.setText("Date de naissance : ");

        jLabelVilleNais.setText("Ville de naissance :");

        jLabelPaysNais.setText("Pays de naissance :");

        jLabelSexe.setText("Sexe : ");

        jLabelDateInsc.setText("Date d'inscritption : ");

        jLabelEtaPre.setText("Etablissement précédent : ");

        jTextFieldDateNais.setText("jTextField1");

        jTextFieldVilleNais.setText("jTextField1");

        jTextFieldPaysNais.setText("jTextField1");

        jTextFieldSexe.setText("jTextField1");

        jTextFieldDateInsc.setText("jTextField1");

        jTextFieldEtaPre.setText("jTextField1");

        javax.swing.GroupLayout jPanelContentIdentiteLayout = new javax.swing.GroupLayout(jPanelContentIdentite);
        jPanelContentIdentite.setLayout(jPanelContentIdentiteLayout);
        jPanelContentIdentiteLayout.setHorizontalGroup(
            jPanelContentIdentiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentIdentiteLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanelContentIdentiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelContentIdentiteLayout.createSequentialGroup()
                        .addComponent(jLabelEtaPre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldEtaPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentIdentiteLayout.createSequentialGroup()
                        .addComponent(jLabelDateInsc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldDateInsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentIdentiteLayout.createSequentialGroup()
                        .addComponent(jLabelSexe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentIdentiteLayout.createSequentialGroup()
                        .addComponent(jLabelPaysNais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPaysNais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentIdentiteLayout.createSequentialGroup()
                        .addComponent(jLabelVilleNais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldVilleNais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentIdentiteLayout.createSequentialGroup()
                        .addComponent(jLabelDateNais)
                        .addGap(105, 105, 105)
                        .addComponent(jTextFieldDateNais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContentIdentiteLayout.setVerticalGroup(
            jPanelContentIdentiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentIdentiteLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanelContentIdentiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateNais)
                    .addComponent(jTextFieldDateNais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentIdentiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVilleNais)
                    .addComponent(jTextFieldVilleNais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentIdentiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPaysNais)
                    .addComponent(jTextFieldPaysNais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentIdentiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSexe)
                    .addComponent(jTextFieldSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentIdentiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateInsc)
                    .addComponent(jTextFieldDateInsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentIdentiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEtaPre)
                    .addComponent(jTextFieldEtaPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(279, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelIdentiteLayout = new javax.swing.GroupLayout(jPanelIdentite);
        jPanelIdentite.setLayout(jPanelIdentiteLayout);
        jPanelIdentiteLayout.setHorizontalGroup(
            jPanelIdentiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdentiteLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanelTitreIdentite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(jPanelIdentiteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContentIdentite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelIdentiteLayout.setVerticalGroup(
            jPanelIdentiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdentiteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitreIdentite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelContentIdentite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneAdmin.addTab("Identité", jPanelIdentite);

        jPanelCoord.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitreCoord.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTitreCoord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitreCoord.setText("COORDONNEES");

        javax.swing.GroupLayout jPanelTitreCoordLayout = new javax.swing.GroupLayout(jPanelTitreCoord);
        jPanelTitreCoord.setLayout(jPanelTitreCoordLayout);
        jPanelTitreCoordLayout.setHorizontalGroup(
            jPanelTitreCoordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreCoordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreCoord, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitreCoordLayout.setVerticalGroup(
            jPanelTitreCoordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreCoordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreCoord, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelContentCoord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jLabelAdr.setText("Adresse : ");

        jLabelCp.setText("Code postal : ");

        jLabelVille.setText("Ville : ");

        jLabelTelDom.setText("Téléphone domicile : ");

        jLabelTelMob.setText("Téléphone mobile : ");

        jLabelMail.setText("Email : ");

        jTextFieldAdr.setText("jTextField1");

        jTextFieldCp.setText("jTextField1");

        jTextFieldVille.setText("jTextField1");

        jTextFieldTelDom.setText("jTextField1");

        jTextFieldTelMob.setText("jTextField1");

        jTextFieldMail.setText("jTextField1");

        javax.swing.GroupLayout jPanelContentCoordLayout = new javax.swing.GroupLayout(jPanelContentCoord);
        jPanelContentCoord.setLayout(jPanelContentCoordLayout);
        jPanelContentCoordLayout.setHorizontalGroup(
            jPanelContentCoordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentCoordLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanelContentCoordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAdr)
                    .addComponent(jLabelCp)
                    .addComponent(jLabelVille)
                    .addComponent(jLabelTelDom)
                    .addComponent(jLabelTelMob)
                    .addComponent(jLabelMail))
                .addGap(96, 96, 96)
                .addGroup(jPanelContentCoordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTelMob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTelDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAdr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContentCoordLayout.setVerticalGroup(
            jPanelContentCoordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentCoordLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanelContentCoordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdr)
                    .addComponent(jTextFieldAdr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentCoordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCp)
                    .addComponent(jTextFieldCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentCoordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVille)
                    .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentCoordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelDom)
                    .addComponent(jTextFieldTelDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentCoordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelMob)
                    .addComponent(jTextFieldTelMob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentCoordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMail)
                    .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCoordLayout = new javax.swing.GroupLayout(jPanelCoord);
        jPanelCoord.setLayout(jPanelCoordLayout);
        jPanelCoordLayout.setHorizontalGroup(
            jPanelCoordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCoordLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanelTitreCoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(jPanelCoordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContentCoord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCoordLayout.setVerticalGroup(
            jPanelCoordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCoordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitreCoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelContentCoord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneAdmin.addTab("Coordonnées", jPanelCoord);

        jLabelTitrePers.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTitrePers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitrePers.setText("PERSONNE RESPONSABLE");

        javax.swing.GroupLayout jPanelTitrePersLayout = new javax.swing.GroupLayout(jPanelTitrePers);
        jPanelTitrePers.setLayout(jPanelTitrePersLayout);
        jPanelTitrePersLayout.setHorizontalGroup(
            jPanelTitrePersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitrePersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitrePers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitrePersLayout.setVerticalGroup(
            jPanelTitrePersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitrePersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitrePers, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelContentPers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jLabelContact1.setText("PREMIER CONTACT");

        jLabelContact1Nom.setText("Nom : ");

        jLabelContact1Prenom.setText("Prénom : ");

        jLabelContact1Adr.setText("Adresse : ");

        jLabelContact1Tel.setText("Téléphone : ");

        jLabelContact1Mail.setText("Email : ");

        jLabelContact2.setText("SECOND CONTACT");

        jLabelContact2Nom.setText("Nom : ");

        jLabelContact2Prenom.setText("Prénom :");

        jLabelContact2Adr.setText("Adresse :");

        jLabelContact2Tel.setText("Téléphone : ");

        jLabelContact2Mail.setText("Email : ");

        jTextFieldContact1Nom.setText("jTextField1");

        jTextFieldContact1Prenom.setText("jTextField1");

        jTextFieldContact1Adr.setText("jTextField1");

        jTextFieldContact1Tel.setText("jTextField1");

        jTextFieldContact1Mail.setText("jTextField1");

        jTextFieldContact2Nom.setText("jTextField1");

        jTextFieldContact2Prenom.setText("jTextField1");

        jTextFieldContact2Adr.setText("jTextField1");

        jTextFieldContact2Tel.setText("jTextField1");

        jTextFieldContact2Mail.setText("jTextField1");

        javax.swing.GroupLayout jPanelContentPersLayout = new javax.swing.GroupLayout(jPanelContentPers);
        jPanelContentPers.setLayout(jPanelContentPersLayout);
        jPanelContentPersLayout.setHorizontalGroup(
            jPanelContentPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentPersLayout.createSequentialGroup()
                .addGroup(jPanelContentPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelContentPersLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabelContact1))
                    .addGroup(jPanelContentPersLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanelContentPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContentPersLayout.createSequentialGroup()
                                .addComponent(jLabelContact1Prenom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldContact1Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContentPersLayout.createSequentialGroup()
                                .addComponent(jLabelContact1Nom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldContact1Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContentPersLayout.createSequentialGroup()
                                .addComponent(jLabelContact1Mail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldContact1Mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContentPersLayout.createSequentialGroup()
                                .addComponent(jLabelContact1Adr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldContact1Adr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContentPersLayout.createSequentialGroup()
                                .addComponent(jLabelContact1Tel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldContact1Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelContentPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContact2)
                    .addGroup(jPanelContentPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelContentPersLayout.createSequentialGroup()
                            .addComponent(jLabelContact2Mail)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldContact2Mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelContentPersLayout.createSequentialGroup()
                            .addComponent(jLabelContact2Tel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldContact2Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelContentPersLayout.createSequentialGroup()
                            .addComponent(jLabelContact2Adr)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldContact2Adr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelContentPersLayout.createSequentialGroup()
                            .addComponent(jLabelContact2Prenom)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldContact2Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelContentPersLayout.createSequentialGroup()
                            .addComponent(jLabelContact2Nom)
                            .addGap(74, 74, 74)
                            .addComponent(jTextFieldContact2Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(159, 159, 159))
        );
        jPanelContentPersLayout.setVerticalGroup(
            jPanelContentPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentPersLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanelContentPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContact1)
                    .addComponent(jLabelContact2))
                .addGap(45, 45, 45)
                .addGroup(jPanelContentPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContact1Nom)
                    .addComponent(jLabelContact2Nom)
                    .addComponent(jTextFieldContact1Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContact2Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContact1Prenom)
                    .addComponent(jLabelContact2Prenom)
                    .addComponent(jTextFieldContact1Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContact2Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContact1Adr)
                    .addComponent(jLabelContact2Adr)
                    .addComponent(jTextFieldContact1Adr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContact2Adr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContact1Tel)
                    .addComponent(jLabelContact2Tel)
                    .addComponent(jTextFieldContact1Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContact2Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContact1Mail)
                    .addComponent(jLabelContact2Mail)
                    .addComponent(jTextFieldContact1Mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContact2Mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(248, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPersLayout = new javax.swing.GroupLayout(jPanelPers);
        jPanelPers.setLayout(jPanelPersLayout);
        jPanelPersLayout.setHorizontalGroup(
            jPanelPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanelTitrePers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(jPanelPersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContentPers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPersLayout.setVerticalGroup(
            jPanelPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitrePers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelContentPers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneAdmin.addTab("Personne responsable", jPanelPers);

        jLabelTitreSante.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTitreSante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitreSante.setText("SANTE");

        javax.swing.GroupLayout jPanelTitreSanteLayout = new javax.swing.GroupLayout(jPanelTitreSante);
        jPanelTitreSante.setLayout(jPanelTitreSanteLayout);
        jPanelTitreSanteLayout.setHorizontalGroup(
            jPanelTitreSanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreSanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreSante, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitreSanteLayout.setVerticalGroup(
            jPanelTitreSanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreSanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreSante, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelContentSante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jLabelNomMed.setText("Nom du médecin traitant :");

        jLabelPrenomMed.setText("Prénom du médecin traitant : ");

        jLabelTelMed.setText("Téléphone :");

        jLabelVacc.setText("Vaccination(s) :");

        jLabelAll.setText("Allergie(s) : ");

        jLabelRem.setText("Remarque(s) médicale(s) : ");

        jTextFieldNomMed.setText("jTextField1");

        jTextFieldPrenomMed.setText("jTextField1");

        jTextFieldTelMed.setText("jTextField1");

        jTextFieldVacc.setText("jTextField1");

        jTextFieldAll.setText("jTextField1");

        jTextFieldRem.setText("jTextField1");

        javax.swing.GroupLayout jPanelContentSanteLayout = new javax.swing.GroupLayout(jPanelContentSante);
        jPanelContentSante.setLayout(jPanelContentSanteLayout);
        jPanelContentSanteLayout.setHorizontalGroup(
            jPanelContentSanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentSanteLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanelContentSanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelContentSanteLayout.createSequentialGroup()
                        .addComponent(jLabelRem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentSanteLayout.createSequentialGroup()
                        .addComponent(jLabelAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentSanteLayout.createSequentialGroup()
                        .addComponent(jLabelVacc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldVacc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentSanteLayout.createSequentialGroup()
                        .addComponent(jLabelTelMed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldTelMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentSanteLayout.createSequentialGroup()
                        .addComponent(jLabelPrenomMed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPrenomMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentSanteLayout.createSequentialGroup()
                        .addComponent(jLabelNomMed)
                        .addGap(120, 120, 120)
                        .addComponent(jTextFieldNomMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContentSanteLayout.setVerticalGroup(
            jPanelContentSanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentSanteLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanelContentSanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomMed)
                    .addComponent(jTextFieldNomMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentSanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrenomMed)
                    .addComponent(jTextFieldPrenomMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentSanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelMed)
                    .addComponent(jTextFieldTelMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentSanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVacc)
                    .addComponent(jTextFieldVacc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentSanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAll)
                    .addComponent(jTextFieldAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContentSanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRem)
                    .addComponent(jTextFieldRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelSanteLayout = new javax.swing.GroupLayout(jPanelSante);
        jPanelSante.setLayout(jPanelSanteLayout);
        jPanelSanteLayout.setHorizontalGroup(
            jPanelSanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSanteLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanelTitreSante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(jPanelSanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContentSante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSanteLayout.setVerticalGroup(
            jPanelSanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitreSante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelContentSante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneAdmin.addTab("Santé", jPanelSante);

        jLabelTitreDoc.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTitreDoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitreDoc.setText("DOCUMENTS");

        javax.swing.GroupLayout jPanelTitreDocLayout = new javax.swing.GroupLayout(jPanelTitreDoc);
        jPanelTitreDoc.setLayout(jPanelTitreDocLayout);
        jPanelTitreDocLayout.setHorizontalGroup(
            jPanelTitreDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreDocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitreDocLayout.setVerticalGroup(
            jPanelTitreDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreDocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelContentDoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        javax.swing.GroupLayout jPanelContentDocLayout = new javax.swing.GroupLayout(jPanelContentDoc);
        jPanelContentDoc.setLayout(jPanelContentDocLayout);
        jPanelContentDocLayout.setHorizontalGroup(
            jPanelContentDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );
        jPanelContentDocLayout.setVerticalGroup(
            jPanelContentDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelDocLayout = new javax.swing.GroupLayout(jPanelDoc);
        jPanelDoc.setLayout(jPanelDocLayout);
        jPanelDocLayout.setHorizontalGroup(
            jPanelDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanelTitreDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(jPanelDocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContentDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDocLayout.setVerticalGroup(
            jPanelDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitreDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelContentDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneAdmin.addTab("Documents", jPanelDoc);

        jButtonAccueil.setText("Accueil");
        jButtonAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccueilActionPerformed(evt);
            }
        });

        jButtonAdmin.setText("Partie Administrative");

        jButtonAca.setText("Partie Académique");
        jButtonAca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcaActionPerformed(evt);
            }
        });

        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaprojet/view/logo-ex-7.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAccueil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jButtonAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPaneAdmin))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccueilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAccueilActionPerformed

    private void jButtonAcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Accueil_1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAca;
    private javax.swing.JButton jButtonAccueil;
    private javax.swing.JButton jButtonAdmin;
    private javax.swing.JLabel jLabelAdr;
    private javax.swing.JLabel jLabelAll;
    private javax.swing.JLabel jLabelContact1;
    private javax.swing.JLabel jLabelContact1Adr;
    private javax.swing.JLabel jLabelContact1Mail;
    private javax.swing.JLabel jLabelContact1Nom;
    private javax.swing.JLabel jLabelContact1Prenom;
    private javax.swing.JLabel jLabelContact1Tel;
    private javax.swing.JLabel jLabelContact2;
    private javax.swing.JLabel jLabelContact2Adr;
    private javax.swing.JLabel jLabelContact2Mail;
    private javax.swing.JLabel jLabelContact2Nom;
    private javax.swing.JLabel jLabelContact2Prenom;
    private javax.swing.JLabel jLabelContact2Tel;
    private javax.swing.JLabel jLabelCp;
    private javax.swing.JLabel jLabelDateInsc;
    private javax.swing.JLabel jLabelDateNais;
    private javax.swing.JLabel jLabelEtaPre;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelMat;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelNomMed;
    private javax.swing.JLabel jLabelPaysNais;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelPrenomMed;
    private javax.swing.JLabel jLabelRem;
    private javax.swing.JLabel jLabelSexe;
    private javax.swing.JLabel jLabelTelDom;
    private javax.swing.JLabel jLabelTelMed;
    private javax.swing.JLabel jLabelTelMob;
    private javax.swing.JLabel jLabelTitreCoord;
    private javax.swing.JLabel jLabelTitreDoc;
    private javax.swing.JLabel jLabelTitreGen;
    private javax.swing.JLabel jLabelTitreIdentite;
    private javax.swing.JLabel jLabelTitrePers;
    private javax.swing.JLabel jLabelTitreSante;
    private javax.swing.JLabel jLabelVacc;
    private javax.swing.JLabel jLabelVille;
    private javax.swing.JLabel jLabelVilleNais;
    private javax.swing.JPanel jPanelContentCoord;
    private javax.swing.JPanel jPanelContentDoc;
    private javax.swing.JPanel jPanelContentGen;
    private javax.swing.JPanel jPanelContentIdentite;
    private javax.swing.JPanel jPanelContentPers;
    private javax.swing.JPanel jPanelContentSante;
    private javax.swing.JPanel jPanelCoord;
    private javax.swing.JPanel jPanelDoc;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JPanel jPanelIdentite;
    private javax.swing.JPanel jPanelPers;
    private javax.swing.JPanel jPanelSante;
    private javax.swing.JPanel jPanelTitreCoord;
    private javax.swing.JPanel jPanelTitreDoc;
    private javax.swing.JPanel jPanelTitreGen;
    private javax.swing.JPanel jPanelTitreIdentite;
    private javax.swing.JPanel jPanelTitrePers;
    private javax.swing.JPanel jPanelTitreSante;
    private javax.swing.JTabbedPane jTabbedPaneAdmin;
    private javax.swing.JTextField jTextFieldAdr;
    private javax.swing.JTextField jTextFieldAll;
    private javax.swing.JTextField jTextFieldContact1Adr;
    private javax.swing.JTextField jTextFieldContact1Mail;
    private javax.swing.JTextField jTextFieldContact1Nom;
    private javax.swing.JTextField jTextFieldContact1Prenom;
    private javax.swing.JTextField jTextFieldContact1Tel;
    private javax.swing.JTextField jTextFieldContact2Adr;
    private javax.swing.JTextField jTextFieldContact2Mail;
    private javax.swing.JTextField jTextFieldContact2Nom;
    private javax.swing.JTextField jTextFieldContact2Prenom;
    private javax.swing.JTextField jTextFieldContact2Tel;
    private javax.swing.JTextField jTextFieldCp;
    private javax.swing.JTextField jTextFieldDateInsc;
    private javax.swing.JTextField jTextFieldDateNais;
    private javax.swing.JTextField jTextFieldEtaPre;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldMat;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldNomMed;
    private javax.swing.JTextField jTextFieldPaysNais;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldPrenomMed;
    private javax.swing.JTextField jTextFieldRem;
    private javax.swing.JTextField jTextFieldSexe;
    private javax.swing.JTextField jTextFieldTelDom;
    private javax.swing.JTextField jTextFieldTelMed;
    private javax.swing.JTextField jTextFieldTelMob;
    private javax.swing.JTextField jTextFieldVacc;
    private javax.swing.JTextField jTextFieldVille;
    private javax.swing.JTextField jTextFieldVilleNais;
    // End of variables declaration//GEN-END:variables
}
